### PR TITLE
adding support for a collector config file.

### LINKED ISSUE #39: Add ability to filter out virtual disks that are detected by smartctl --scan
Discussed in #30

### LINKED ISSUE #45: [FEAT] Allow option to pass device type so devices not found in scan can be included
First, I'd like to say that Scrutiny is such a great idea.  Thank for you for creating this!!

**Feature Request**
It would be awesome if there was a way to pass the device type to Scrutiny so that it can collect details on drives that the smartctl utility can't identify on it's own (due to USB bridge identification limits, etc).

**Context**

I deployed this in Docker to a little home server I run, and mapped in 3 devices in the config file as such:

      - device=/dev/sda
      - device=/dev/sdb
      - device=/dev/sdc

When I opened the Scrutiny UI after doing a scan, only the first two internal drives were visible.  The last (/dev/sdc) is an external USB drive.  I poked around and saw that it can be problematic for smartctl to get the details for external drives.  However, if I could find and pass the correct device type for the USB bridge, it might work.

I was able to identify the correct value to pass for my particular drive, which allowed the retrieval of SMART data from my external drive from terminal.  If I could provide configuration detail that the device is of type **sat**, hopefully I'll be able to monitor that external drive as well with Scrutiny.  Below are the outputs of various commands I ran as I tested my theory.

**sudo smartctl --scan**
```
/dev/sda -d scsi # /dev/sda, SCSI device
/dev/sdb -d scsi # /dev/sdb, SCSI device
```

**sudo smartctl -i /dev/sdc**
```
smartctl 7.1 2019-12-30 r5022 [x86_64-linux-5.4.0-42-generic] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/sdc: Unknown USB bridge [0x04e8:0x6123 (0x202)]
Please specify device type with the -d option.

Use smartctl -h to get a usage summary
```

**sudo smartctl -i /dev/sdc -d sat**
```
smartctl 7.1 2019-12-30 r5022 [x86_64-linux-5.4.0-42-generic] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Seagate Barracuda 7200.14 (AF)
Device Model:     ST2000DM001-1E6164
Serial Number:    W1E86G1H
LU WWN Device Id: 5 000c50 073eb6239
Firmware Version: SC48
User Capacity:    2,000,398,934,016 bytes [2.00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    7200 rpm
Form Factor:      3.5 inches
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ATA8-ACS T13/1699-D revision 4
SATA Version is:  SATA 3.0, 6.0 Gb/s (current: 3.0 Gb/s)
Local Time is:    Sun Sep 27 19:10:19 2020 CDT
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
```

### LINKED ISSUE #46: [BUG]smartctl checksum errors
Hi,

i'm using the linuxserver.io docker image (latest tag) and currently am getting the following errors when running "scrutiny-collector-metrics run"

`root@abc9cc899866:/# scrutiny-collector-metrics run

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
AnalogJ/scrutiny/metrics                               dev-0.1.13

INFO[0000] Verifying required tools                      type=metrics
INFO[0000] Sending detected devices to API, for filtering & validation  type=metrics
INFO[0000] Main: Waiting for workers to finish           type=metrics
INFO[0000] Collecting smartctl results for sdd           type=metrics
INFO[0000] Collecting smartctl results for sda           type=metrics
INFO[0000] Collecting smartctl results for sdb           type=metrics
INFO[0000] Collecting smartctl results for sdc           type=metrics
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      1
    ],
    "svn_revision": "5022",
    "platform_info": "x86_64-linux-4.14.24-qnap",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-a",
      "-j",
      "/dev/sda"
    ],
    "exit_status": 4
  },
  "device": {
    "name": "/dev/sda",
    "info_name": "/dev/sda",
    "type": "scsi",
    "protocol": "SCSI"
  },
  "vendor": "WDC",
  "product": "WD100EMAZ-00WJTA",
  "model_name": "WDC WD100EMAZ-00WJTA",
  "revision": "83.H",
  "scsi_version": "SPC-3",
  "user_capacity": {
    "blocks": 19532873728,
    "bytes": 10000831348736
  },
  "logical_block_size": 512,
  "physical_block_size": 4096,
  "rotation_rate": 5400,
  "form_factor": {
    "scsi_value": 2,
    "name": "3.5 inches"
  },
  "serial_number": "2YJDN6SD",
  "device_type": {
    "scsi_value": 0,
    "name": "disk"
  },
  "local_time": {
    "time_t": 1601292556,
    "asctime": "Mon Sep 28 20:29:16 2020 KST"
  },
  "temperature": {
    "current": 0,
    "drive_trip": 0
  }
}
ERRO[0000] smartctl returned an error code (4) while processing sda  type=metrics
ERRO[0000] smartctl detected a checksum error            type=metrics
INFO[0000] Publishing smartctl results for unknown       type=metrics
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      1
    ],
    "svn_revision": "5022",
    "platform_info": "x86_64-linux-4.14.24-qnap",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-a",
      "-j",
      "/dev/sdb"
    ],
    "exit_status": 4
  },
  "device": {
    "name": "/dev/sdb",
    "info_name": "/dev/sdb",
    "type": "scsi",
    "protocol": "SCSI"
  },
  "vendor": "WDC",
  "product": "WD100EMAZ-00WJTA",
  "model_name": "WDC WD100EMAZ-00WJTA",
  "revision": "83.H",
  "scsi_version": "SPC-3",
  "user_capacity": {
    "blocks": 19532873728,
    "bytes": 10000831348736
  },
  "logical_block_size": 512,
  "physical_block_size": 4096,
  "rotation_rate": 5400,
  "form_factor": {
    "scsi_value": 2,
    "name": "3.5 inches"
  },
  "serial_number": "2YJ8S5BD",
  "device_type": {
    "scsi_value": 0,
    "name": "disk"
  },
  "local_time": {
    "time_t": 1601292556,
    "asctime": "Mon Sep 28 20:29:16 2020 KST"
  },
  "temperature": {
    "current": 0,
    "drive_trip": 0
  }
}
ERRO[0000] smartctl returned an error code (4) while processing sdb  type=metrics
ERRO[0000] smartctl detected a checksum error            type=metrics
INFO[0000] Publishing smartctl results for unknown       type=metrics
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      1
    ],
    "svn_revision": "5022",
    "platform_info": "x86_64-linux-4.14.24-qnap",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-a",
      "-j",
      "/dev/sdd"
    ],
    "exit_status": 4
  },
  "device": {
    "name": "/dev/sdd",
    "info_name": "/dev/sdd",
    "type": "scsi",
    "protocol": "SCSI"
  },
  "vendor": "WDC",
  "product": "WD100EMAZ-00WJTA",
  "model_name": "WDC WD100EMAZ-00WJTA",
  "revision": "83.H",
  "scsi_version": "SPC-3",
  "user_capacity": {
    "blocks": 19532873728,
    "bytes": 10000831348736
  },
  "logical_block_size": 512,
  "physical_block_size": 4096,
  "rotation_rate": 5400,
  "form_factor": {
    "scsi_value": 2,
    "name": "3.5 inches"
  },
  "serial_number": "2YJDUTKD",
  "device_type": {
    "scsi_value": 0,
    "name": "disk"
  },
  "local_time": {
    "time_t": 1601292556,
    "asctime": "Mon Sep 28 20:29:16 2020 KST"
  },
  "temperature": {
    "current": 0,
    "drive_trip": 0
  }
}
ERRO[0000] smartctl returned an error code (4) while processing sdd  type=metrics
ERRO[0000] smartctl detected a checksum error            type=metrics
INFO[0000] Publishing smartctl results for unknown       type=metrics
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      1
    ],
    "svn_revision": "5022",
    "platform_info": "x86_64-linux-4.14.24-qnap",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-a",
      "-j",
      "/dev/sdc"
    ],
    "exit_status": 4
  },
  "device": {
    "name": "/dev/sdc",
    "info_name": "/dev/sdc",
    "type": "scsi",
    "protocol": "SCSI"
  },
  "vendor": "WDC",
  "product": "WD100EMAZ-00WJTA",
  "model_name": "WDC WD100EMAZ-00WJTA",
  "revision": "83.H",
  "scsi_version": "SPC-3",
  "user_capacity": {
    "blocks": 19532873728,
    "bytes": 10000831348736
  },
  "logical_block_size": 512,
  "physical_block_size": 4096,
  "rotation_rate": 5400,
  "form_factor": {
    "scsi_value": 2,
    "name": "3.5 inches"
  },
  "serial_number": "JEHN4M1N",
  "device_type": {
    "scsi_value": 0,
    "name": "disk"
  },
  "local_time": {
    "time_t": 1601292556,
    "asctime": "Mon Sep 28 20:29:16 2020 KST"
  },
  "temperature": {
    "current": 0,
    "drive_trip": 0
  }
}
ERRO[0000] smartctl returned an error code (4) while processing sdc  type=metrics
ERRO[0000] smartctl detected a checksum error            type=metrics
INFO[0000] Publishing smartctl results for unknown       type=metrics
INFO[0001] Main: Completed                               type=metrics
root@abc9cc899866:/# `

After running, I can only see /dev/sda in the web UI and it has no details (SMART reports as failed).

I'm running this on a QNAP TS453Be.

Thanks,

### LINKED ISSUE #48: [BUG] Cannot override incorrect device type from smartctl --scan, breaks Synology
Hi, I'm trying scrutiny on a Synology NAS (using Docker) and I notice that it does not correctly gets smart details for the internal disks.

Running the collector, I see that its trying to query the disk using scsi by the results of "smartctl -a -j /dev/sdb":

```
  "device": {
    "name": "/dev/sdb",
    "info_name": "/dev/sdb",
    "type": "scsi",
    "protocol": "SCSI"
  },
```

However, in a synology, the query must be done in "**sat**" mode (SCSI to ATA Translation) ("scsi" does not return smart values and "ata" does not work).

Here are the ouputs of the three modes:


**scsi results:**
```
root@a26318c5f903:/scrutiny/bin# smartctl -d scsi --all /dev/sdb                                        
smartctl 7.0 2018-12-30 r4883 [x86_64-linux-3.10.105] (local build)                                     
Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org                             
                                                                                                        
=== START OF INFORMATION SECTION ===                                                                    
Vendor:               HGST                                                                              
Product:              HDN726040ALE614                                                                   
Revision:             APGN                                                                              
Compliance:           SPC-3                                                                             
User Capacity:        4,000,787,030,016 bytes [4.00 TB]                                                 
Logical block size:   512 bytes                                                                         
Physical block size:  4096 bytes                                                                        
LU is fully provisioned                                                                                 
Rotation Rate:        7200 rpm                                                                          
Form Factor:          3.5 inches                                                                        
Logical Unit id:      0x5000cca25def1764                                                                
Serial number:        K4KXXXXX                                                                          
Device type:          disk                                                                              
Local Time is:        Mon Sep 28 21:00:47 2020 UTC                                                      
SMART support is:     Unavailable - device lacks SMART capability.                                      
                                                                                                        
=== START OF READ SMART DATA SECTION ===                                                                
Current Drive Temperature:     0 C                                                                      
Drive Trip Temperature:        0 C                                                                      
                                                                                                        
Error Counter logging not supported                                                                     
                                                                                                        
                                                                                                        
[GLTSD (Global Logging Target Save Disable) set. Enable Save with '-S on']                              
Device does not support Self Test logging    
```

**ata results:**
```
root@a26318c5f903:/scrutiny/bin# smartctl -d ata --all /dev/sdb                                         
smartctl 7.0 2018-12-30 r4883 [x86_64-linux-3.10.105] (local build)                                     
Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org                             
                                                                                                        
Read Device Identity failed: Permission denied                                                          
                                                                                                        
A mandatory SMART command failed: exiting. To continue, add one or more '-T permissive' options.       
``` 


**sat results:**
```
root@a26318c5f903:/scrutiny/bin# smartctl -d sat --all /dev/sdb                                         
smartctl 7.0 2018-12-30 r4883 [x86_64-linux-3.10.105] (local build)                                     
Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org                             
                                                                                                        
=== START OF INFORMATION SECTION ===                                                                    
Model Family:     HGST Deskstar NAS                                                                     
Device Model:     HGST HDN726040ALE614                                                                  
Serial Number:    K4KXXXXX                                                                              
LU WWN Device Id: 5 000cca 25def1764                                                                    
Firmware Version: APGNW7JH                                                                              
User Capacity:    4,000,787,030,016 bytes [4.00 TB]                                                     
Sector Sizes:     512 bytes logical, 4096 bytes physical                                                
Rotation Rate:    7200 rpm                                                                              
Form Factor:      3.5 inches                                                                            
Device is:        In smartctl database [for details use: -P show]                                       
ATA Version is:   ACS-2, ATA8-ACS T13/1699-D revision 4                                                 
SATA Version is:  SATA 3.1, 6.0 Gb/s (current: 3.0 Gb/s)                                                
Local Time is:    Mon Sep 28 20:57:22 2020 UTC                                                          
SMART support is: Available - device has SMART capability.                                              
SMART support is: Enabled                                                                               
                                                                                                        
=== START OF READ SMART DATA SECTION ===                                                                
SMART overall-health self-assessment test result: PASSED              

                                                                                                        
General SMART Values:                                                                                   
Offline data collection status:  (0x82) Offline data collection activity                                
                                        was completed without error.                                    
                                        Auto Offline Data Collection: Enabled.                          
Self-test execution status:      193 Load_Cycle_Count        0x0012   100   100   000    Old_age   Alway
s       -       1072                                                                                    
 12 Power_Cycle_Count       0x0032   100   100   000    Old_age   Always       -       38               
192 Power-Off_Retract_Count 0x0032   100   100   000    Old_age   Always       -       1072             
(   0)  The previous self-test routine completed                                                        
                                        without error or no self-test has ever                          
                                        been run.                                                       
Total time to complete Offline                                                                          
data collection:                (  113) seconds.                                                        
Offline data collection                                                                                 
capabilities:                    (0x5b) SMART execute Offline immediate.                                
                                        Auto Offline data collection on/off support.                    
                                        Suspend Offline collection upon new                             
                                        command.                                                        
                                        Offline surface scan supported.                                 
                                        Self-test supported.                                            
                                        No Conveyance Self-test supported.                              
                                        Selective Self-test supported.                                  
SMART capabilities:            (0x0003) Saves SMART data before entering                                
                                        power-saving mode.                                              
                                        Supports SMART auto save timer.                                 
Error logging capability:        (0x01) Error logging supported.                                        
                                        General Purpose Logging supported.                              
Short self-test routine                                                                                 
recommended polling time:        (   2) minutes.                                                        
Extended self-test routine                                                                              
recommended polling time:        ( 571) minutes.                                                        
SCT capabilities:              (0x003d) SCT Status supported.                                           
                                        SCT Error Recovery Control supported.                           
                                        SCT Feature Control supported.                                  
                                        SCT Data Table supported.                                       
                                                              
SMART Attributes Data Structure revision number: 16                                                     
Vendor Specific SMART Attributes with Thresholds:                                                       
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE        
  1 Raw_Read_Error_Rate     0x000b   100   100   016    Pre-fail  Always       -       0                
  2 Throughput_Performance  0x0005   138   138   054    Pre-fail  Offline      -       100              
  3 Spin_Up_Time            0x0007   149   149   024    Pre-fail  Always       -       361 (Average 357)
  4 Start_Stop_Count        0x0012   100   100   000    Old_age   Always       -       50               
  5 Reallocated_Sector_Ct   0x0033   100   100   005    Pre-fail  Always       -       0                
  7 Seek_Error_Rate         0x000b   100   100   067    Pre-fail  Always       -       0                
  8 Seek_Time_Performance   0x0005   128   128   020    Pre-fail  Offline      -       18               
  9 Power_On_Hours          0x0012   097   097   000    Old_age   Always       -       24956            
 10 Spin_Retry_Count        0x0013   100   100   060    Pre-fail  Always       -       0                
194 Temperature_Celsius     0x0002   162   162   000    Old_age   Always       -       37 (Min/Max 22/52
)                                                                                                       
196 Reallocated_Event_Count 0x0032   100   100   000    Old_age   Always       -       0                
197 Current_Pending_Sector  0x0022   100   100   000    Old_age   Always       -       0                
198 Offline_Uncorrectable   0x0008   100   100   000    Old_age   Offline      -       0                
199 UDMA_CRC_Error_Count    0x000a   200   200   000    Old_age   Always       -       0                
                                                                                                        
SMART Error Log Version: 1                                                                              
No Errors Logged                                                                                        
                              
SMART Self-test log structure revision number 1                                                         
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error         
# 1  Extended offline    Completed without error       00%     24307         -                          
# 2  Extended offline    Completed without error       00%     23563         -                          
# 3  Extended offline    Completed without error       00%     22820         -                          
# 4  Extended offline    Completed without error       00%     22098         -                          
# 5  Extended offline    Completed without error       00%     21354         -                          
# 6  Extended offline    Completed without error       00%     20636         -                          
# 7  Extended offline    Completed without error       00%     19894         -                          
# 8  Extended offline    Completed without error       00%     19195         -                          
# 9  Extended offline    Completed without error       00%     18453         -                          
#10  Extended offline    Completed without error       00%     17707         -                          
#11  Extended offline    Completed without error       00%     16987         -                          
#12  Extended offline    Completed without error       00%     16244         -                          
#13  Extended offline    Completed without error       00%     15523         -                          
#14  Extended offline    Completed without error       00%     14780         -                          
#15  Extended offline    Completed without error       00%     14036         -                          
#16  Extended offline    Completed without error       00%     13319         -                          
#17  Extended offline    Completed without error       00%     12576         -                          
#18  Extended offline    Completed without error       00%     11852         -                          
#19  Extended offline    Completed without error       00%     11113         -                          
#20  Extended offline    Completed without error       00%     10441         -                          
#21  Extended offline    Completed without error       00%      9698         -                          
                                                                                                        
SMART Selective self-test log data structure revision number 1                                          
 SPAN  MIN_LBA  MAX_LBA  CURRENT_TEST_STATUS                                                            
    1        0        0  Not_testing                                                                    
    2        0        0  Not_testing                                                                    
    3        0        0  Not_testing                                                                    
    4        0        0  Not_testing                                                                    
    5        0        0  Not_testing                                                                    
Selective self-test flags (0x0):                                                                        
  After scanning selected spans, do NOT read-scan remainder of disk.                                    
If Selective self-test is pending on power-up, resume after 0 minute delay.                    
```

### PR DESCRIPTION
**Pull request by AnalogJ**
This is still a WIP. But here's an example of what the `collector` config file will look like:

```yaml
# Commented Scrutiny Configuration File
#
# The default location for this file is /scrutiny/config/collector.yaml.
# In some cases to improve clarity default values are specified,
# uncommented. Other example values are commented out.
#
# When this file is parsed by Scrutiny, all configuration file keys are
# lowercased automatically. As such, Configuration keys are case-insensitive,
# and should be lowercase in this file to be consistent with usage.


######################################################################
# Version
#
# version specifies the version of this configuration file schema, not
# the scrutiny binary. There is only 1 version available at the moment
version: 1

# This block allows you to override/customize the settings for devices detected by
# Scrutiny via `smartctl --scan`
# See the "--device=TYPE" section of https://linux.die.net/man/8/smartctl
# type can be a 'string' or a 'list'
devices:
  # example for forcing device type detection for a single disk
  - device: /dev/sda
    type: 'sat'

  # example to show how to ignore a specific disk/device.
  - device: /dev/sda
    ignore: true

  # examples showing how to force smartctl to detect disks inside a raid array/virtual disk
  - device: /dev/bus/0
    type:
      - megaraid,14
      - megaraid,15
      - megaraid,18
      - megaraid,19
      - megaraid,20
      - megaraid,21

  - device: /dev/twa0
    type:
      - 3ware,0
      - 3ware,1
      - 3ware,2
      - 3ware,3
      - 3ware,4
      - 3ware,5

```

You can test it out yourself by using the `analogj/scrutiny:detect` docker image. Then just create a `collector.yaml` file in the host directory you bind to `/scrutiny/config`:

```
docker run -it --rm -p 8080:8080 \
-v /run/udev:/run/udev:ro \
-v /tmp/scrutiny-config:/scrutiny/config \
--cap-add SYS_RAWIO \
--device=/dev/sda \
--device=/dev/sdb \
--name scrutiny \
analogj/scrutiny
```

---

# Current Changelog

Adding ability to specify host identifier (label), that is updated on every collector run.
Can be specified by `host-id` CLI or `COLLECTOR_HOST_ID` env var.

Created a config class, interface and associated tests.

Created a "TransformDetectedDrives" function, that will allow users to insert drives not detected by Smarctl --scan, ignore drives that they dont want, and override smartctl device type.

Added Upsert functionality when registering devices.

Replaced "github.com/jinzhu/gorm" with "gorm.io/gorm" (ORM location moved, was using incorrect lib url)
Removed machineid library.

fixes #46
fixes #45
fixes #48 
fixes #39
related #50 - adds a HostID to the database that is updated on every collector run. Not displayed in UI yet.

### CODE REVIEW

**Comment by PrplHaz4** [comment]
This config is working great for me for 2 SAS and 2 SATA drives on an H240 controller as HBA.  I'm also running scrutiny on multiple hosts in docker with the standalone connector and not seeing any obvious issues yet.  Nice work!

```
devices:
  - device: /dev/sdc
    type: 'sat'
  - device: /dev/sdd
    type: 'sat'

  - device: /dev/sg0
    type:
      - cciss,0
      - cciss,1
```

**Comment by mrtumnus** [comment]
Works for me!  I'm using the 3ware type for 7 SATA drives, and it works great!  Good to see all my drives are healthy :)

**Comment by AnalogJ** [comment]
Awesome! Thanks for the feedback :) 
I'll merge this and make a new release.

**Comment by elliottback** [comment]
Thanks for the patch, confirm this is also working great for my Synology DS1513 + 2 expansion units.

**Comment by auricom** [comment]
Hello,

First of all, wonderful piece of software :+1: 

I run Scrutiny on a Kubernetes cluster, where it is not possible to passthrough devices to unprivileged containers. I'm running scrutiny with `privileged: true`. The scrutiny collector container see all the node devices, including the kubernetes volumes that are virtual devices (smartctl detect them as SCSI drives, as seen in `smartctl --scan` :
...
/dev/sdab -d scsi # /dev/sdab, SCSI device
/dev/sdad -d scsi # /dev/sdad, SCSI device
...

It seems that I should be using the "ignore: true" features on "devices" in collector.yaml , but I cannot know how many volumes will be present on each drives, so I cannot ignore specific devices.

I would like something like this to be working :
```
version: 1
devices:
  - type: 'nvme'
  - type: 'sat'
  - type: 'scsi'
    ignore: true
```

It seems that this is not working, as scrutiny-web still reports dozen of unwanted ISCI drives.
Do you know if this use case is manageable with the new feature you released ?

Thanks

**Comment by AnalogJ** [comment]
Hey @auricom 

Unfortunately there's no way to block a device type completely, only individual devices. 
You do bring up an interesing use-case for it though. 
Can you open up a new feature request and copy-paste your comment? I think this would be useful for other users as well, and I don't want to lose it in a closed-issue.

**Comment by auricom** [comment]
hello,
thanks I'm glad you consider this use case to be interesting. I created a new feature request.

**Comment by FinalDoom** [comment]
Glad this is in here, hopefully makes it to the readme at some point. I got some nice metrics (woo, cool, great app) for my hp server running hpsa (HP Storage Array RAID) type--took a bit of digging into smartctl to find: 

    smartctl -a -d cciss,0 /dev/cciss/c0d0    (cciss driver under Linux)
    smartctl -a -d cciss,0 /dev/sg2    (hpsa or hpahcisr drivers under Linux)

but putting the -d stuff in the config file worked a charm. Maybe it'll show up if anyone searches and runs into the same thing. I got here from the dell megaraid thread.

Also I'm dumb and didn't read the comments fully in the sample config. XD Woulda made it a little more obvious.

**Pull request merged**
