### PR TITLE
Upgrade shoutrrr to 0.6.1

### PR DESCRIPTION
**Pull request by davralin**
Could you upgrade shoutrrr to a newer version?

This brings in support for more notification libraries, for instance matrix  - which I'm looking for.

### CODE REVIEW

**Comment by AnalogJ** [comment]
Thanks for the PR! 🎉  

looks like you forgot to update the `go.sum` file. 
can you run `go mod tidy` and commit that file?

**Comment by davralin** [comment]
> Thanks for the PR! tada
> 
> looks like you forgot to update the `go.sum` file. can you run `go mod tidy` and commit that file?

Forgot? No, I just have no idea what I'm doing! :)
I hoped it was as easy as bumping the version number for it to happen.

I'll see what I can make of it.

**Comment by AnalogJ** [comment]
oh in that case, let me see if I can edit your PR branch. I think github has a feature like that.

**Comment by davralin** [comment]
I successfully ran `go mod tidy` in a container, that did bring in several other things - I'm guessing these are updated modules from upstream projects.

You probably also want those perhaps, so I didn't remove them.

Let me know if you want me to just bring in the stuff I need for shoutrrr to be upgraded.

**Comment by AnalogJ** [comment]
this is great, thanks! I'll make sure it's included in the next release (`v0.5.1`) 🥳

**Comment by davralin** [comment]
Do you have any plans to update to 0.5.1 any time soon?

An updated apprise-library is key for me to use this, and I really need something to monitor my drives.

**Comment by AnalogJ** [comment]
hey @davralin 
Sorry for the delay getting this change implemented, I've been busy with another project. 
I just released v0.6.0 which includes this change. Can you pull it down and test it?

**Comment by davralin** [comment]
Took me quite some time, but all good! I have successfull notifications on matrix now :)

**Pull request closed without merging**
